name: cek_ongkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.9.2

dependencies: 
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dropdown_search: 5.0.6
  dio: 5.9.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

